### ISSUE TITLE
Adds namespace to animation keyframes

### ISSUE THREAD

**Issue by rmhowe** [topaxi/postcss-selector-namespace#3]
If I define keyframes within the CSS as follows:
```
@keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```
and run it through postcss-selector-namespace with `.foo` as the namespace, the output will be:
```
@keyframes fadeIn {
  .foo 0% {
    opacity: 0;
  }
  .foo 100% {
    opacity: 1;
  }
}
```
breaking the animation.

I had a quick look through the code to see if there might be a nice way to handle this, not sure if PostCSS handles keyframe declarations differently to other rules though, if it's as simple as adding a regex check for `@(-webkit-|-moz-|-o-)?keyframes` somewhere and then preventing further rule walking for descendants? Sorry not very familiar with PostCSS plugins. Great plugin though!

**Comment by topaxi** [comment]
Thanks for reporting. Fixed in `1.2.6` 👍
